services:
  postgres:
    image: postgres:16-alpine
    container_name: silentsupply-db
    network_mode: host
    environment:
      POSTGRES_DB: silentsupply
      POSTGRES_USER: silentsupply
      POSTGRES_PASSWORD: silentsupply
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
